# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 471755b8032b6f4f118b49bf0446bd197f65b21d50fe95e11c809cb887a288d52e3e7586af1a2b6775ffdba3ba6884895d76ff1118f89274f4a72a74d7ac5836

test:
  secret_key_base: e396683283f187730acd4e7550414ac0fe9d39d2f9adc12792f32c5024397b38ec8b9c2040a770a71e7f5f450857ef961ed875d50d948b799e6479003116692e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
